-- Updating the FK_VALIDATION_STAMP_BRANCH constraint
ALTER TABLE VALIDATION_STAMP DROP CONSTRAINT FK_VALIDATION_STAMP_PROMOTION_LEVEL;
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_PROMOTION_LEVEL FOREIGN KEY (PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL (ID) ON DELETE SET NULL;
