-- Saving the filters
CREATE TABLE ACCOUNT_FILTER (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT INTEGER NOT NULL,
  BRANCH INTEGER NOT NULL,
  FILTERNAME VARCHAR(80) NOT NULL,
  FILTER LONGVARCHAR NOT NULL,
  CONSTRAINT FK_ACCOUNT_FILTER_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_ACCOUNT_FILTER_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_ACCOUNT_FILTER UNIQUE (ACCOUNT, BRANCH, FILTERNAME)
);

-- @rollback
DROP TABLE IF EXISTS ACCOUNT_FILTER;
