-- A validation stamp belongs to a branch
ALTER TABLE VALIDATION_STAMP ADD COLUMN BRANCH INTEGER NOT NULL;
ALTER TABLE VALIDATION_STAMP DROP CONSTRAINT UQ_VALIDATION_STAMP;
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT UQ_VALIDATION_STAMP_BRANCH UNIQUE (BRANCH, NAME);
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT fk_VALIDATION_STAMP_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID);
