-- Signature for comments
ALTER TABLE COMMENT ADD COLUMN AUTHOR VARCHAR(80) NOT NULL;
ALTER TABLE COMMENT ADD COLUMN AUTHOR_ID INTEGER NULL;
ALTER TABLE COMMENT ADD COLUMN COMMENT_TIMESTAMP TIMESTAMP NOT NULL;
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES ACCOUNTS (ID) ON DELETE SET NULL;
-- @mysql
-- See update 26
