-- Selection of validation stamps
CREATE TABLE VALIDATION_STAMP_SELECTION (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT INTEGER NOT NULL,
  VALIDATION_STAMP INTEGER NOT NULL,
  CONSTRAINT FK_VALIDATION_STAMP_SELECTION_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE,
  CONSTRAINT FK_VALIDATION_STAMP_SELECTION_VALIDATION_STAMP FOREIGN KEY (VALIDATION_STAMP) REFERENCES VALIDATION_STAMP (ID) ON DELETE CASCADE
);-- @mysql
-- See update 26
