-- Adds a owner field on the validation stamp
ALTER TABLE VALIDATION_STAMP ADD OWNER_ID INTEGER NULL;
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_OWNER FOREIGN KEY (OWNER_ID) REFERENCES ACCOUNTS (ID) ON DELETE SET NULL;
