-- Validation stamps for the dashboard

CREATE TABLE DASHBOARD_VALIDATION_STAMP (
  BRANCH           INTEGER NOT NULL,
  VALIDATION_STAMP INTEGER NOT NULL,
  CONSTRAINT PK_DASHBOARD_VALIDATION_STAMP PRIMARY KEY (BRANCH, VALIDATION_STAMP),
  CONSTRAINT FK_DASHBOARD_VALIDATION_STAMP_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE CASCADE,
  CONSTRAINT FK_DASHBOARD_VALIDATION_STAMP_VALIDATION_STAMP FOREIGN KEY (VALIDATION_STAMP) REFERENCES VALIDATION_STAMP (ID) ON DELETE CASCADE
);

-- @rollback

DROP TABLE IF EXISTS DASHBOARD_VALIDATION_STAMP;
-- @mysql
-- See update 26
