-- Build clean-up configuration

CREATE TABLE BUILD_CLEANUP (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  BRANCH INTEGER NOT NULL,
  RETENTION INTEGER NOT NULL,
  CONSTRAINT PK_BUILD_CLEANUP PRIMARY KEY (ID),
  CONSTRAINT UQ_BUILD_CLEANUP UNIQUE (BRANCH),
  CONSTRAINT FK_BUILD_CLEANUP_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE CASCADE
);

CREATE TABLE BUILD_CLEANUP_PROMOTION (
  BUILD_CLEANUP INTEGER NOT NULL,
  PROMOTION_LEVEL INTEGER NOT NULL,
  CONSTRAINT PK_BUILD_CLEANUP_PROMOTION PRIMARY KEY (BUILD_CLEANUP, PROMOTION_LEVEL),
  CONSTRAINT FK_BUILD_CLEANUP_PROMOTION_BUILD_CLEANUP FOREIGN KEY (BUILD_CLEANUP) REFERENCES BUILD_CLEANUP (ID) ON DELETE CASCADE,
  CONSTRAINT FK_BUILD_CLEANUP_PROMOTION_PROMOTION_LEVEL FOREIGN KEY (PROMOTION_LEVEL) REFERENCES (PROMOTION_LEVEL) ON DELETE CASCADE
);

-- @rollback

DROP TABLE IF EXISTS BUILD_CLEANUP;
DROP TABLE IF EXISTS BUILD_CLEANUP_PROMOTION;
-- @mysql
-- See update 26
