-- Updating the FK_VALIDATION_STAMP_BRANCH constraint
ALTER TABLE VALIDATION_STAMP DROP CONSTRAINT fk_VALIDATION_STAMP_BRANCH;
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE CASCADE;
