-- Signature for promoted runs

ALTER TABLE PROMOTED_RUN ADD CREATION TIMESTAMP NULL BEFORE DESCRIPTION;
ALTER TABLE PROMOTED_RUN ADD AUTHOR_ID INTEGER NULL BEFORE DESCRIPTION;
ALTER TABLE PROMOTED_RUN ADD AUTHOR VARCHAR(80) NULL BEFORE DESCRIPTION;

ALTER TABLE PROMOTED_RUN ADD CONSTRAINT FK_PROMOTION_RUN_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES ACCOUNTS (ID) ON DELETE SET NULL;

UPDATE PROMOTED_RUN PR SET CREATION = (SELECT E.EVENT_TIMESTAMP  FROM EVENTS E WHERE E.EVENT_TYPE  = 'PROMOTED_RUN_CREATED' AND E.BUILD = PR.BUILD AND E.PROMOTION_LEVEL = PR.PROMOTION_LEVEL);
UPDATE PROMOTED_RUN PR SET AUTHOR_ID = (SELECT E.AUTHOR_ID  FROM EVENTS E WHERE E.EVENT_TYPE  = 'PROMOTED_RUN_CREATED' AND E.BUILD = PR.BUILD AND E.PROMOTION_LEVEL = PR.PROMOTION_LEVEL);
UPDATE PROMOTED_RUN PR SET AUTHOR = (SELECT E.AUTHOR  FROM EVENTS E WHERE E.EVENT_TYPE  = 'PROMOTED_RUN_CREATED' AND E.BUILD = PR.BUILD AND E.PROMOTION_LEVEL = PR.PROMOTION_LEVEL);

ALTER TABLE PROMOTED_RUN ALTER COLUMN CREATION SET NOT NULL;
ALTER TABLE PROMOTED_RUN ALTER COLUMN AUTHOR SET NOT NULL;

-- @rollback

ALTER TABLE PROMOTED_RUN DROP COLUMN IF EXISTS CREATION;
ALTER TABLE PROMOTED_RUN DROP COLUMN IF EXISTS AUTHOR_ID;
ALTER TABLE PROMOTED_RUN DROP COLUMN IF EXISTS AUTHOR;
-- @mysql
-- See update 26
