-- Support for MySQL
-- @mysql    

CREATE TABLE BUILD_CLEANUP(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BRANCH INTEGER NOT NULL,
    RETENTION INTEGER NOT NULL,
	CONSTRAINT PK_BUILD_CLEANUP PRIMARY KEY(ID)
	);    

CREATE TABLE PROMOTED_RUN(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PROMOTION_LEVEL INTEGER NOT NULL,
    BUILD INTEGER NOT NULL,
    CREATION TIMESTAMP NOT NULL,
    AUTHOR_ID INTEGER,
    AUTHOR VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
	CONSTRAINT PK_PROMOTED_RUN PRIMARY KEY(ID)
	);        

CREATE TABLE EVENTS(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    AUTHOR VARCHAR(80) NOT NULL,
    AUTHOR_ID INTEGER,
    EVENT_TIMESTAMP TIMESTAMP NOT NULL,
    EVENT_TYPE VARCHAR(40) NOT NULL,
    ACCOUNT INTEGER,
    PROJECT INTEGER,
    BRANCH INTEGER,
    BUILD INTEGER,
    PROMOTION_LEVEL INTEGER,
    VALIDATION_STAMP INTEGER,
    VALIDATION_RUN INTEGER,
    COMMENT INTEGER,
    SENT BOOLEAN,
	CONSTRAINT PK_EVENT PRIMARY KEY(ID)
	);     

CREATE TABLE COMMENT(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(1000) NOT NULL,
    PROJECT INTEGER,
    BRANCH INTEGER,
    BUILD INTEGER,
    PROMOTION_LEVEL INTEGER,
    VALIDATION_STAMP INTEGER,
    VALIDATION_RUN INTEGER,
    AUTHOR VARCHAR(80) NOT NULL,
    AUTHOR_ID INTEGER,
    COMMENT_TIMESTAMP TIMESTAMP NOT NULL,
	CONSTRAINT PK_COMMENT PRIMARY KEY(ID)
	);  

CREATE TABLE PROPERTIES(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EXTENSION VARCHAR(40) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    VALUE VARCHAR(300) NOT NULL,
    PROJECT INTEGER,
    BRANCH INTEGER,
    BUILD INTEGER,
    PROMOTION_LEVEL INTEGER,
    VALIDATION_STAMP INTEGER,
    VALIDATION_RUN INTEGER,
	CONSTRAINT PK_PROPERTIES PRIMARY KEY(ID)
	);            

CREATE TABLE PROJECT(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
	CONSTRAINT PK_PROJECT PRIMARY KEY(ID)
	);  

CREATE TABLE BRANCH(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PROJECT INTEGER NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
	CONSTRAINT PK_BRANCH PRIMARY KEY(ID)
	);    

CREATE TABLE BUILD(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BRANCH INTEGER NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
	CONSTRAINT PK_BUILD PRIMARY KEY(ID)
	);      

CREATE TABLE VALIDATION_STAMP_SELECTION(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ACCOUNT INTEGER NOT NULL,
    VALIDATION_STAMP INTEGER NOT NULL,
	CONSTRAINT PK_VALIDATION_STAMP_SELECTION PRIMARY KEY(ID)
);              

CREATE TABLE ACCOUNTS(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(16) NOT NULL,
    FULLNAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ROLENAME VARCHAR(40) NOT NULL,
    MODE VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(140),
	CONSTRAINT PK_ACCOUNTS PRIMARY KEY(ID)
	);

CREATE TABLE VALIDATION_STAMP(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PROMOTION_LEVEL INTEGER,
    NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    BRANCH INTEGER NOT NULL,
    IMAGE VARBINARY(4096),
    ORDERNB INTEGER NOT NULL,
    OWNER_ID INTEGER,
	CONSTRAINT PK_VALIDATION_STAMP PRIMARY KEY(ID)
	);

CREATE TABLE VALIDATION_RUN_STATUS(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    VALIDATION_RUN INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    AUTHOR VARCHAR(80) NOT NULL,
    AUTHOR_ID INTEGER,
    STATUS_TIMESTAMP TIMESTAMP NOT NULL,
	CONSTRAINT PK_VALIDATION_RUN_STATUS PRIMARY KEY(ID)
	);      

CREATE TABLE VALIDATION_RUN(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    VALIDATION_STAMP INTEGER NOT NULL,
    BUILD INTEGER NOT NULL,
    DESCRIPTION VARCHAR(1000),
    RUN_ORDER INTEGER NOT NULL,
	CONSTRAINT PK_VALIDATION_RUN PRIMARY KEY(ID)
	);    

CREATE TABLE SUBSCRIPTION(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ACCOUNT INTEGER NOT NULL,
    PROJECT INTEGER,
    BRANCH INTEGER,
    BUILD INTEGER,
    PROMOTION_LEVEL INTEGER,
    VALIDATION_STAMP INTEGER,
    VALIDATION_RUN INTEGER,	
	CONSTRAINT PK_SUBSCRIPTION PRIMARY KEY(ID)
);

CREATE TABLE BUILD_CLEANUP_PROMOTION(
    BUILD_CLEANUP INTEGER NOT NULL,
    PROMOTION_LEVEL INTEGER NOT NULL,
	CONSTRAINT PK_BUILD_CLEANUP_PROMOTION PRIMARY KEY(BUILD_CLEANUP, PROMOTION_LEVEL)
	);      

CREATE TABLE PROMOTION_LEVEL(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    BRANCH INTEGER NOT NULL,
    NAME VARCHAR(80) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    IMAGE VARBINARY(4096),
    LEVELNB INTEGER,
    AUTOPROMOTE BOOLEAN NOT NULL,
	CONSTRAINT PK_PROMOTION_LEVEL PRIMARY KEY(ID)
	);  

CREATE TABLE DASHBOARD_VALIDATION_STAMP(
    BRANCH INTEGER NOT NULL,
    VALIDATION_STAMP INTEGER NOT NULL,
	CONSTRAINT PK_DASHBOARD_VALIDATION_STAMP PRIMARY KEY(BRANCH, VALIDATION_STAMP)
	);      

CREATE TABLE EVENT_VALUES(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EVENT INTEGER NOT NULL,
    PROP_NAME VARCHAR(20) NOT NULL,
    PROP_VALUE VARCHAR(80) NOT NULL,
	CONSTRAINT PK_EVENT_VALUES PRIMARY KEY(ID)
	);        

CREATE TABLE CONFIGURATION(
    NAME VARCHAR(40) NOT NULL,
    VALUE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CONFIGURATION PRIMARY KEY(NAME)
	);    

ALTER TABLE EVENT_VALUES ADD CONSTRAINT UQ_EVENT_VALUES UNIQUE(EVENT, PROP_NAME);               
ALTER TABLE BRANCH ADD CONSTRAINT UQ_BRANCH UNIQUE(PROJECT, NAME);              
ALTER TABLE PROJECT ADD CONSTRAINT UQ_PROJECT UNIQUE(NAME);     
ALTER TABLE PROMOTION_LEVEL ADD CONSTRAINT UQ_PROMOTION_LEVEL UNIQUE(BRANCH, NAME);             
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT UQ_VALIDATION_STAMP_BRANCH UNIQUE(BRANCH, NAME);    
ALTER TABLE BUILD_CLEANUP ADD CONSTRAINT UQ_BUILD_CLEANUP UNIQUE(BRANCH);       
ALTER TABLE BUILD ADD CONSTRAINT UQ_BUILD UNIQUE(BRANCH, NAME); 
ALTER TABLE ACCOUNTS ADD CONSTRAINT UQ_ACCOUNTS UNIQUE(NAME);   
ALTER TABLE PROMOTED_RUN ADD CONSTRAINT UQ_PROMOTED_RUN UNIQUE(PROMOTION_LEVEL, BUILD);         
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_ACCOUNT FOREIGN KEY(ACCOUNT) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE;  
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;        
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;            
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;         
ALTER TABLE EVENT_VALUES ADD CONSTRAINT FK_EVENT_VALUES_EVENT FOREIGN KEY(EVENT) REFERENCES EVENTS(ID) ON DELETE CASCADE;        
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_VALIDATION_RUN FOREIGN KEY(VALIDATION_RUN) REFERENCES VALIDATION_RUN(ID) ON DELETE CASCADE;              
ALTER TABLE VALIDATION_RUN ADD CONSTRAINT FK_VALIDATION_RUN_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;     
ALTER TABLE DASHBOARD_VALIDATION_STAMP ADD CONSTRAINT FK_DASHBOARD_VALIDATION_STAMP_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;          
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_AUTHOR FOREIGN KEY(AUTHOR_ID) REFERENCES ACCOUNTS(ID) ON DELETE SET NULL;             
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;      
ALTER TABLE PROMOTED_RUN ADD CONSTRAINT FK_PROMOTION_RUN_AUTHOR FOREIGN KEY(AUTHOR_ID) REFERENCES ACCOUNTS(ID) ON DELETE SET NULL;               
ALTER TABLE PROMOTION_LEVEL ADD CONSTRAINT FK_PROMOTION_LEVEL_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;
ALTER TABLE VALIDATION_STAMP_SELECTION ADD CONSTRAINT FK_VALIDATION_STAMP_SELECTION_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;            
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_PROJECT FOREIGN KEY(PROJECT) REFERENCES PROJECT(ID) ON DELETE CASCADE;
ALTER TABLE DASHBOARD_VALIDATION_STAMP ADD CONSTRAINT FK_DASHBOARD_VALIDATION_STAMP_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;            
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;          
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;     
ALTER TABLE VALIDATION_STAMP_SELECTION ADD CONSTRAINT FK_VALIDATION_STAMP_SELECTION_ACCOUNT FOREIGN KEY(ACCOUNT) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE;      
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;     
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_PROJECT FOREIGN KEY(PROJECT) REFERENCES PROJECT(ID) ON DELETE CASCADE;             
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;      
ALTER TABLE PROMOTED_RUN ADD CONSTRAINT FK_PROMOTED_RUN_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;           
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_AUTHOR_ID FOREIGN KEY(AUTHOR_ID) REFERENCES ACCOUNTS(ID) ON DELETE SET NULL;       
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;             
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;              
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;               
ALTER TABLE BRANCH ADD CONSTRAINT FK_BRANCH_PROJECT FOREIGN KEY(PROJECT) REFERENCES PROJECT(ID) ON DELETE CASCADE;               
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_OWNER FOREIGN KEY(OWNER_ID) REFERENCES ACCOUNTS(ID) ON DELETE SET NULL;          
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_VALIDATION_RUN FOREIGN KEY(VALIDATION_RUN) REFERENCES VALIDATION_RUN(ID) ON DELETE CASCADE;           
ALTER TABLE BUILD ADD CONSTRAINT FK_BUILD_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;    
ALTER TABLE BUILD_CLEANUP_PROMOTION ADD CONSTRAINT FK_BUILD_CLEANUP_PROMOTION_BUILD_CLEANUP FOREIGN KEY(BUILD_CLEANUP) REFERENCES BUILD_CLEANUP(ID) ON DELETE CASCADE;           
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;   
ALTER TABLE VALIDATION_RUN_STATUS ADD CONSTRAINT FK_VALIDATION_RUN_STATUS_VALIDATION_RUN FOREIGN KEY(VALIDATION_RUN) REFERENCES VALIDATION_RUN(ID) ON DELETE CASCADE;            
ALTER TABLE VALIDATION_RUN ADD CONSTRAINT FK_VALIDATION_RUN_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;    
ALTER TABLE VALIDATION_STAMP ADD CONSTRAINT FK_VALIDATION_STAMP_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE SET NULL;  
ALTER TABLE BUILD_CLEANUP ADD CONSTRAINT FK_BUILD_CLEANUP_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;    
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_PROJECT FOREIGN KEY(PROJECT) REFERENCES PROJECT(ID) ON DELETE CASCADE;       
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;           
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_BRANCH FOREIGN KEY(BRANCH) REFERENCES BRANCH(ID) ON DELETE CASCADE;   
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENT_COMMENT FOREIGN KEY(COMMENT) REFERENCES COMMENT(ID) ON DELETE CASCADE;
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;        
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_VALIDATION_STAMP FOREIGN KEY(VALIDATION_STAMP) REFERENCES VALIDATION_STAMP(ID) ON DELETE CASCADE;  
ALTER TABLE BUILD_CLEANUP_PROMOTION ADD CONSTRAINT FK_BUILD_CLEANUP_PROMOTION_PROMOTION_LEVEL FOREIGN KEY(PROMOTION_LEVEL) REFERENCES PROMOTION_LEVEL(ID) ON DELETE CASCADE;
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_VALIDATION_RUN FOREIGN KEY(VALIDATION_RUN) REFERENCES VALIDATION_RUN(ID) ON DELETE CASCADE;        
ALTER TABLE PROPERTIES ADD CONSTRAINT FK_PROPERTIES_VALIDATION_RUN FOREIGN KEY(VALIDATION_RUN) REFERENCES VALIDATION_RUN(ID) ON DELETE CASCADE;  
ALTER TABLE SUBSCRIPTION ADD CONSTRAINT FK_SUBSCRIPTION_PROJECT FOREIGN KEY(PROJECT) REFERENCES PROJECT(ID) ON DELETE CASCADE;   
ALTER TABLE PROMOTED_RUN ADD CONSTRAINT FK_PROMOTED_RUN_BUILD FOREIGN KEY(BUILD) REFERENCES BUILD(ID) ON DELETE CASCADE;         
