-- Global authorizations
CREATE TABLE GLOBAL_AUTHORIZATION (
  ACCOUNT INTEGER NOT NULL,
  FN VARCHAR(40) NOT NULL,
  CONSTRAINT GLOBAL_AUTHORIZATION_PK PRIMARY KEY (ACCOUNT, FN),
  CONSTRAINT GLOBAL_AUTHORIZATION_FK_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ID) ON DELETE CASCADE
);

-- @rollback
DROP TABLE IF EXISTS GLOBAL_AUTHORIZATION;
