-- Run order as a column

ALTER TABLE VALIDATION_RUN ADD COLUMN RUN_ORDER INTEGER NULL;
UPDATE VALIDATION_RUN R SET RUN_ORDER = (SELECT COUNT(*) FROM VALIDATION_RUN RS WHERE RS.BUILD  = R.BUILD AND RS.VALIDATION_STAMP = R.VALIDATION_STAMP AND RS.ID <= R.ID);
ALTER TABLE VALIDATION_RUN ALTER COLUMN RUN_ORDER SET NOT NULL;

-- @rollback

ALTER TABLE VALIDATION_RUN DROP COLUMN RUN_ORDER;
