-- Custom dashboards

CREATE TABLE DASHBOARD (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(80) NOT NULL,
  CONSTRAINT DASHBOARD_PK PRIMARY KEY (ID)
);

CREATE TABLE DASHBOARD_CONFIG (
  DASHBOARD INTEGER NOT NULL,
  BRANCH INTEGER NOT NULL,
  CONSTRAINT DASHBOARD_CONFIG_PK PRIMARY KEY (DASHBOARD, BRANCH),
  CONSTRAINT DASHBOARD_CONFIG_FK_DASHBOARD FOREIGN KEY (DASHBOARD) REFERENCES DASHBOARD (ID) ON DELETE CASCADE,
  CONSTRAINT DASHBOARD_CONFIG_FK_BRANCH FOREIGN KEY (BRANCH) REFERENCES BRANCH (ID) ON DELETE CASCADE
);

-- @rollback

DROP TABLE IF EXISTS DASHBOARD_CONFIG;
DROP TABLE IF EXISTS DASHBOARD;
