-- Deleting everything related to project groups
DELETE FROM PROJECT_GROUP;

ALTER TABLE COMMENT DROP COLUMN PROJECT_GROUP;
ALTER TABLE EVENTS DROP COLUMN PROJECT_GROUP;
ALTER TABLE PROJECT DROP COLUMN PROJECT_GROUP;
ALTER TABLE PROPERTIES DROP COLUMN PROJECT_GROUP;
ALTER TABLE SUBSCRIPTION DROP COLUMN PROJECT_GROUP;

DROP TABLE PROJECT_GROUP;
