-- Timestamp for promoted runs

ALTER TABLE PROMOTED_RUN ADD CREATION TIMESTAMP NULL BEFORE DESCRIPTION;

UPDATE PROMOTED_RUN PR SET CREATION = (SELECT E.EVENT_TIMESTAMP  FROM EVENTS E WHERE E.EVENT_TYPE  = 'BUILD_CREATED' AND E.BUILD = PR.BUILD);

ALTER TABLE PROMOTED_RUN ALTER COLUMN CREATION SET NOT NULL;

-- @rollback

ALTER TABLE PROMOTED_RUN DROP COLUMN IF EXISTS CREATION;
