package net.ontrack.service;

import net.ontrack.core.model.Ack;
import net.ontrack.core.model.ExportData;
import net.ontrack.core.model.ImportResult;
import org.springframework.web.multipart.MultipartFile;

import java.util.Collection;

public interface ExportService {

    String exportLaunch(Collection<Integer> projectIds);

    Ack exportCheck(String uuid);

    ExportData exportDownload(String uuid);

    /**
     * Launches the import of projects from a file that contains
     * some exported projects.
     *
     * @param file File to import
     * @return UUID to be used in {@link #importCheck(String)}
     */
    String importLaunch(MultipartFile file);

    /**
     * Launches the import of projects
     *
     * @param importData Data to import
     * @return UUID to be used in {@link #importCheck(String)}
     */
    String importLaunch(ExportData importData);

    /**
     * Checks if an import is finished or not.
     *
     * @param uuid UUID of the import task (generated by {@link #importLaunch(net.ontrack.core.model.ExportData)})
     * @return The result of the check
     */
    ImportResult importCheck(String uuid);
}
